services:
  spring-app:
    image: technicaltest:latest
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: default
  
  spring-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: mvn test
    depends_on:
      - spring-app
